### GENERATE SSL CERTIFICATE (CERT-MANAGER) ###
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: mz-spin-demo-ssl
#   namespace: mzmushko
# spec:
#   secretName: mz-spin-demo-ssl
#   issuerRef:
#     name: ClusterIssuer
#     kind: Issuer
#   commonName: mz-spin-demo.azure-omnicloud.com
#   dnsNames:
#   - mz-spin-demo.azure-omnicloud.com
# ---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: spinnaker-ui-gateway
  namespace: mzmushko
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http-spinnaker-ui
        protocol: HTTP
      hosts:
        - mz-spin-demo.azure-omnicloud.com
### IN CASE OF USING SECURE CONNECTION ###
    #   tls:
    #     httpsRedirect: true
    # - port:
    #     number: 443
    #     name: https-spinnaker-ui
    #     protocol: HTTPS
    #   hosts:
    #     - spin-demo.zullzorrander.com
    #   tls:
    #     mode: SIMPLE
    #     credentialName: zull-spin-demo-ssl
---
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: spinnaker-ui-dr
  namespace: mzmushko
spec:
  host: spin-deck
  trafficPolicy:
    tls: {}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: spinnaker-ui-vs
  namespace: mzmushko
spec:
  hosts:
    - mz-spin-demo.azure-omnicloud.com
  gateways:
    - spinnaker-ui-gateway
  http:
    - route:
      - destination:
          host: spin-deck
          port:
            number: 9000