apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zull-spin-api-demo-ssl
  namespace: mzmushko
spec:
  secretName: zull-spin-api-demo-ssl
  issuerRef:
    name: ClusterIssuer
    kind: Issuer
  commonName: spin-api-demo.zullzorrander.com
  dnsNames:
  - spin-api-demo.zullzorrander.com
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: spinnaker-api-gateway
  namespace: mzmushko
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http-spinnaker-api
        protocol: HTTP
      hosts:
        - spin-api-demo.zullzorrander.com
      tls:
        httpsRedirect: true
    - port:
        number: 443
        name: https-spinnaker-api
        protocol: HTTPS
      hosts:
        - spin-api-demo.zullzorrander.com
      tls:
        mode: SIMPLE
        credentialName: zull-spin-api-demo-ssl
---
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: spinnaker-api-dr
  namespace: mzmushko
spec:
  host: spin-gate
  trafficPolicy:
    tls: {}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: spinnaker-api-vs
  namespace: mzmushko
spec:
  hosts:
    - spin-api-demo.zullzorrander.com
  gateways:
    - spinnaker-api-gateway
  http:
    - route:
      - destination:
          host: spin-gate
          port:
            number: 8084